var HtmlWebPackPlugin = require('html-webpack-plugin');

var HtmlWebPackPluginConfig = new HtmlWebPackPlugin({

    template: __dirname +  '/index.html',

    filename: 'index.html', // file name of html generated by webpack in build folder

    inject: 'body' // newly generated script will be placed in <body> tag

});

module.exports = {

    entry: __dirname + '/src/entry.js',

    module: { //Each "loader" that you add to the loaders array will represent 
              //a transformation that your code will go through before reaching the browser
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            }
        ]
    },

    output: {
        filename: 'transformed.js',
        path: __dirname + '/build'
    },

    plugins:[HtmlWebPackPluginConfig]
};
